"""
Pentagonal numbers are generated by the formula,
Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However,
their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which
their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?
"""

from math import sqrt


def is_pentagonal(n):
    return ((1 + sqrt(1 + (24 * n)))/6).is_integer()


not_found = True
i = 1
while not_found:
    i += 1
    n = (i * ((3 * i) - 1))//2
    for j in range(i - 1, 0, -1):
        m = (j * ((3 * j) - 1))//2
        if (is_pentagonal(n - m) and is_pentagonal(n + m)):
            result = n - m
            not_found = False
print(result)
